
if(WIN32)
	if(CMAKE_SIZEOF_VOID_P EQUAL 8)
		set(JDF_OUTPUT_WIN_NAME Win64)
	else()
		set(JDF_OUTPUT_WIN_NAME Win32)
	endif()
	if (MSVC11)
		set(JDF_MSVC_FOLDER VC11)
	elseif (MSVC10)
		set(JDF_MSVC_FOLDER VC10)
	elseif(MSVC90)
		set(JDF_MSVC_FOLDER VC9)
	elseif(MSVC80)
		set(JDF_MSVC_FOLDER VC8)
	else()
		message(SEND_ERROR "Unsupported MSVC version")
	endif()

	set(JDF_OUTPUT_PATH_BASE ${CMAKE_CURRENT_LIST_DIR}/bin/${JDF_OUTPUT_WIN_NAME}/${JDF_MSVC_FOLDER})
	set(JDF_CMAKE_DEBUG_POSTFIX _D)
else()
	if(APPLE)
		set(JDF_ARCH universal)
	else()
		if(CMAKE_SIZEOF_VOID_P EQUAL 8)
			set(JDF_ARCH x64)
		else()
			set(JDF_ARCH x86)
		endif()
	endif()
	if(APPLE)
		set(JDF_MAC_OR_LINUX Mac)
	else()
		set(JDF_MAC_OR_LINUX Linux)
	endif()
	set(JDF_OUTPUT_PATH_BASE ${CMAKE_CURRENT_LIST_DIR}/bin/${JDF_MAC_OR_LINUX}/${JDF_ARCH})	
endif()

set(JDF_OUTPUT_PATH_DEBUG   ${JDF_OUTPUT_PATH_BASE}/Debug)
set(JDF_OUTPUT_PATH_RELEASE ${JDF_OUTPUT_PATH_BASE}/Release)

macro(_jdflib_set_output_directories TARGET)
	if(MSVC)
		set_target_properties(
			${TARGET} PROPERTIES
			RUNTIME_OUTPUT_DIRECTORY ${JDF_OUTPUT_PATH_BASE}
			ARCHIVE_OUTPUT_DIRECTORY ${JDF_OUTPUT_PATH_BASE}
			LIBRARY_OUTPUT_DIRECTORY ${JDF_OUTPUT_PATH_BASE}		
		)	
	else()
		set_target_properties(
			${TARGET} PROPERTIES
			RUNTIME_OUTPUT_DIRECTORY_DEBUG ${JDF_OUTPUT_PATH_DEBUG}
			ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${JDF_OUTPUT_PATH_DEBUG}
			LIBRARY_OUTPUT_DIRECTORY_DEBUG ${JDF_OUTPUT_PATH_DEBUG}
			RUNTIME_OUTPUT_DIRECTORY_RELEASE ${JDF_OUTPUT_PATH_RELEASE}
			ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${JDF_OUTPUT_PATH_RELEASE}
			LIBRARY_OUTPUT_DIRECTORY_RELEASE ${JDF_OUTPUT_PATH_RELEASE}
		)	
	endif()
endmacro()

